<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Explore groups</name>
   <tag></tag>
   <elementGuidId>4d68db7d-3d86-4da5-b62f-ab26ed66288b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-1qhqijd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='button'])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b823ae81-6c92-4b30-b108-53e20e822016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1qhqijd</value>
      <webElementGuid>11452c5e-dbd8-4fa4-8bb9-4bb290dbaab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ebca2b7-9ba4-4952-9fd7-c115e7b17a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/r/app/group/list/explore</value>
      <webElementGuid>b93dfa52-125b-4827-839f-fc83d3da6a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Explore groups</value>
      <webElementGuid>54f397ed-0946-4b79-a601-848beb4f353d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-182mik5&quot;]/div[@class=&quot;css-11scn02&quot;]/div[@class=&quot;css-11scn02&quot;]/div[2]/div[@class=&quot;css-19ze3iu&quot;]/div[@class=&quot;css-ernoat&quot;]/div[@class=&quot;css-jwbl0q&quot;]/div[@class=&quot;css-13qpzon&quot;]/span[@class=&quot;css-1g8t6mq&quot;]/div[@class=&quot;css-11scn02&quot;]/a[@class=&quot;css-1qhqijd&quot;]</value>
      <webElementGuid>7088b886-adea-4b19-9faf-f487dce3cef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='button'])[14]</value>
      <webElementGuid>049dfba0-1de5-4bf7-8539-742b952fdc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div[2]/div[2]/div/div[3]/div/div/span/div/a</value>
      <webElementGuid>47f513dc-218a-4efc-a6eb-c8e2e10a2e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups you’ve joined, created or are managing will appear here'])[1]/following::a[1]</value>
      <webElementGuid>3537b669-509b-4eff-8ae6-15e26c826afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to groups'])[1]/following::a[1]</value>
      <webElementGuid>3c7351e1-9084-4a35-9433-d3b5d44c66a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/r/app/group/list/explore')])[2]</value>
      <webElementGuid>2e47347d-3b64-4945-82dc-3e01b165feef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
      <webElementGuid>3da6b669-b618-4bbc-92cf-ab1138fa9172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @href = '/r/app/group/list/explore' and (text() = 'Explore groups' or . = 'Explore groups')]</value>
      <webElementGuid>5afadf1c-d05d-4bdf-b4e0-c1ca7a5af324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
