<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administer</name>
   <tag></tag>
   <elementGuidId>e32aebb1-a190-44b6-81b8-4136cde79637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='downshift-1-menu']/div/div[9]/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3a9fe65-d7af-401f-9a29-62cd0f96a9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1576srd</value>
      <webElementGuid>8e11e1a0-6530-46de-954b-5403ec162b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administer</value>
      <webElementGuid>fb8b5680-82fc-4cf7-9ba8-270d9545cb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-1-menu&quot;)/div[@class=&quot;css-55kzg5&quot;]/div[@class=&quot;css-11scn02&quot;]/a[@class=&quot;css-1didwnz&quot;]/span[@class=&quot;css-16evdls&quot;]/span[@class=&quot;css-1576srd&quot;]</value>
      <webElementGuid>c0cd6c48-b8e4-4732-bcf9-fb16a839d76f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downshift-1-menu']/div/div[9]/a/span/span</value>
      <webElementGuid>12ce8ec4-2bda-4914-b53e-6afa5fffaaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insights'])[1]/following::span[2]</value>
      <webElementGuid>78068b24-0a1c-4484-b3c0-7f5bf91dfab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all portals'])[1]/following::span[4]</value>
      <webElementGuid>862c4d43-c627-458e-b934-498a77e5974a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[1]/preceding::span[1]</value>
      <webElementGuid>bea697cb-e1a8-44ca-a85b-28627fd747fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::span[3]</value>
      <webElementGuid>13aad777-dcb4-4255-b6ac-f18c1884c644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administer']/parent::*</value>
      <webElementGuid>e1cf2a55-17a6-4ccc-ad78-f58dbc82d5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a/span/span</value>
      <webElementGuid>567b87c4-fc6f-4913-9329-21990e03cee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Administer' or . = 'Administer')]</value>
      <webElementGuid>6358061d-a5a3-45e0-b071-eef8c99f5d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
