<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_RA</name>
   <tag></tag>
   <elementGuidId>ca5758ea-7856-4745-8726-2925507d5510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-1-label > span.css-xrduwu > div.css-19lwx2q > span.css-m3910k</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='downshift-1-label']/span/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>848f4d02-2380-4961-8a6e-277dcf77c872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-m3910k</value>
      <webElementGuid>0ea44581-a495-4047-95b9-d50804a80475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RA</value>
      <webElementGuid>3f3cc22d-91a8-454c-92b0-5b9feb3b5802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;box has-top-nav&quot;]/div[@class=&quot;ap-navbar-container ap-navbar-topnav&quot;]/div[1]/react-top-menu[1]/div[@class=&quot;css-1hay3xq&quot;]/div[@class=&quot;css-6mjyip&quot;]/div[@class=&quot;css-1i3csc6&quot;]/div[@class=&quot;css-11scn02&quot;]/button[@id=&quot;downshift-1-label&quot;]/span[@class=&quot;css-xrduwu&quot;]/div[@class=&quot;css-19lwx2q&quot;]/span[@class=&quot;css-m3910k&quot;]</value>
      <webElementGuid>2c9c587e-5e96-40f6-919d-96512f939a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='downshift-1-label']/span/div/span</value>
      <webElementGuid>0810038d-83ea-4979-9f67-13e6cc19f047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My teaching'])[1]/following::span[2]</value>
      <webElementGuid>ff8ef42d-affa-4a63-b1c1-8822ebb45623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My team'])[1]/following::span[4]</value>
      <webElementGuid>5d0978d6-e24b-4952-8f18-6619c4462805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Team'])[1]/preceding::span[1]</value>
      <webElementGuid>b69a4596-3c75-432f-a028-7dec9dc6088b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::span[2]</value>
      <webElementGuid>def88284-7596-4f3f-a061-b527fea756d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button/span/div/span</value>
      <webElementGuid>1f7c5249-c6a1-4f23-9b1f-7d192430eb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'RA' or . = 'RA')]</value>
      <webElementGuid>7dc0b845-48bb-4475-9b18-733c1a1a4630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
