<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Groups</name>
   <tag></tag>
   <elementGuidId>98eed3e6-b2cd-4612-8e9b-7a384aa138d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.css-ixs343</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/a[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7817e7d-77ae-49aa-aedb-028e38a09297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ixs343</value>
      <webElementGuid>4a8a2c9a-7df3-4919-85ae-8a64ee9eb241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Groups</value>
      <webElementGuid>b2ba58c2-a235-419a-a695-5b79b8476d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1chuy90&quot;]/div[@class=&quot;css-1yaviln&quot;]/div[@class=&quot;css-100ae4h&quot;]/a[@class=&quot;css-bc0q3d&quot;]/div[@class=&quot;css-qj5jx&quot;]/span[@class=&quot;css-ixs343&quot;]</value>
      <webElementGuid>49c6eda9-ebb0-45c4-a07b-9b031a9819c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/a[2]/div/span</value>
      <webElementGuid>3ce3c56c-2ab3-4133-abac-dc7f631dfdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[2]/following::span[1]</value>
      <webElementGuid>504e9508-acef-4635-87e0-7e34ad2940e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[2]</value>
      <webElementGuid>3bb2fb3a-1264-41e5-8676-d2257c9a93a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My playlists'])[1]/preceding::span[1]</value>
      <webElementGuid>e30ff127-c476-4d59-b43f-a18192a182a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My learning'])[1]/preceding::span[2]</value>
      <webElementGuid>542d9831-bb26-416f-9bd3-ded6ca0b6066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>3c2ee1ae-cbfc-4e57-a9d8-0f6b009eea63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Groups' or . = 'Groups')]</value>
      <webElementGuid>2bae4d50-20ac-411f-bd14-8830d3df5406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
