<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Email</name>
   <tag></tag>
   <elementGuidId>61ca7b69-d98e-443f-8a20-681e649de855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-nu7g3i > span.css-xrduwu > div.css-lq2eq0 > div.css-1i3csc6 > span.css-11zqsye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/div/div/div[2]/div/div/div[2]/button/span/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b943cdd2-97b4-4428-8e02-d8fe9dfa5bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11zqsye</value>
      <webElementGuid>42879c82-5f14-4cf5-8f2f-05d1ef211ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>ff0676a5-311a-4ce3-98ff-bc055a9d5d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1fy77jw&quot;]/div[@class=&quot;css-86byde&quot;]/div[@class=&quot;css-52ab7y&quot;]/div[@class=&quot;css-42fspv&quot;]/div[@class=&quot;css-ugubj7&quot;]/div[@class=&quot;css-gu8bh2&quot;]/div[@class=&quot;css-1m7yml8&quot;]/div[@class=&quot;css-1m7yml8&quot;]/div[@class=&quot;css-1jcfi37&quot;]/div[@class=&quot;css-2o2ki1&quot;]/button[@class=&quot;css-nu7g3i&quot;]/span[@class=&quot;css-xrduwu&quot;]/div[@class=&quot;css-lq2eq0&quot;]/div[@class=&quot;css-1i3csc6&quot;]/span[@class=&quot;css-11zqsye&quot;]</value>
      <webElementGuid>8e947c4e-dbea-47d3-8af3-fd7a8d9bdc08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/div/div/div[2]/div/div/div[2]/button/span/div/div[2]/span</value>
      <webElementGuid>f8fcd458-bac2-4496-8393-9a7995926c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft'])[1]/following::span[2]</value>
      <webElementGuid>995c17d7-911c-4cec-afe5-9070b2353228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/following::span[4]</value>
      <webElementGuid>99df2652-4224-4af8-80b9-9cbd546816b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('By continuing you agree to Cloud Development Resources', &quot;'&quot;, 's')])[1]/preceding::span[1]</value>
      <webElementGuid>607ffdbe-54de-4a9d-bf3d-18a64fa9f3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/preceding::span[1]</value>
      <webElementGuid>a5d98860-59ab-49d9-b49c-c907b360ca0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email']/parent::*</value>
      <webElementGuid>ddef7c36-eef2-429d-87fb-dc3068c06270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/div/div[2]/span</value>
      <webElementGuid>7f226dcf-41e6-4811-9c46-b7a0704407b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Email' or . = 'Email')]</value>
      <webElementGuid>b1b83026-4a86-4e5e-a223-7ee0bdc81f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
