<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Groups_css-1ve3oum</name>
   <tag></tag>
   <elementGuidId>18259428-2f72-4b19-9f17-063a9f34f5ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-1j94st9 > span.css-xrduwu > img.css-1ve3oum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div/react-top-menu/div[2]/div/a/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5eaa999b-e9b7-445b-a066-7359072f72ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ve3oum</value>
      <webElementGuid>0bf8d326-c63e-41ff-87af-90cb5d66da30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/go1/image/upload/v1614811302/t4ok2f2xalfdzyv0esmj.png</value>
      <webElementGuid>6517560e-4a37-4f2a-86cb-b4b75a1b2ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>portal-icon</value>
      <webElementGuid>eead281f-f618-4fb5-8aee-1c2f2bfeca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;box has-top-nav&quot;]/div[@class=&quot;ap-navbar-container ap-navbar-topnav&quot;]/div[1]/react-top-menu[1]/div[@class=&quot;css-1hay3xq&quot;]/div[@class=&quot;css-6mjyip&quot;]/a[@class=&quot;css-1j94st9&quot;]/span[@class=&quot;css-xrduwu&quot;]/img[@class=&quot;css-1ve3oum&quot;]</value>
      <webElementGuid>f3d6494f-5735-47aa-8853-0cdc5fb44e10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/react-top-menu/div[2]/div/a/span/img</value>
      <webElementGuid>f1583802-5cd9-49d7-991f-7a5f0418c527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://res.cloudinary.com/go1/image/upload/v1614811302/t4ok2f2xalfdzyv0esmj.png')])[2]</value>
      <webElementGuid>7104a947-4182-43b3-b1d7-9118656f90e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span/img</value>
      <webElementGuid>4c8df0d1-7d07-43f9-894f-efd4f77e0738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/go1/image/upload/v1614811302/t4ok2f2xalfdzyv0esmj.png']</value>
      <webElementGuid>f3a9e49f-19d0-4895-80d3-72d75e0a80c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
