<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My playlists</name>
   <tag></tag>
   <elementGuidId>e2ede8d6-4c5b-4986-8f38-116c728b25ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-azx51g > a.css-m3tj2n > span.css-xrduwu > span.css-osb9h9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[3]/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f160f223-5bb4-424f-94ce-5105e60f9b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-osb9h9</value>
      <webElementGuid>cf2c4bf1-125b-453b-a01f-8da5fab54fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My playlists</value>
      <webElementGuid>877be50d-f738-4e38-9759-e5a06a238d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-182mik5&quot;]/div[@class=&quot;css-1hay3xq&quot;]/div[@class=&quot;css-6mjyip&quot;]/div[@class=&quot;css-azx51g&quot;]/a[@class=&quot;css-m3tj2n&quot;]/span[@class=&quot;css-xrduwu&quot;]/span[@class=&quot;css-osb9h9&quot;]</value>
      <webElementGuid>2e2f7c4b-10aa-46f6-b380-9d55d464bd9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[3]/a/span/span</value>
      <webElementGuid>f7965b7e-b4ca-48b8-93dd-c7201ac6d12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[2]/following::span[2]</value>
      <webElementGuid>3ef1e856-9c7d-4c48-a773-0bac8a5d0d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[2]/following::span[4]</value>
      <webElementGuid>75012fb8-16ca-4122-a07a-a6d94cf3baf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My learning'])[1]/preceding::span[1]</value>
      <webElementGuid>ace71e95-cfe5-41d9-af84-7955b8c1a60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My team'])[1]/preceding::span[3]</value>
      <webElementGuid>529b79d3-64be-405f-8bcf-d6ed9d3a49ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My playlists']/parent::*</value>
      <webElementGuid>e32b5a7d-296c-4e00-960b-a99f96e8d7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/a/span/span</value>
      <webElementGuid>0494e953-7ecd-4c61-8647-b6b9a27a097a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My playlists' or . = 'My playlists')]</value>
      <webElementGuid>c891d595-6733-4dc5-89af-5a7b2e216121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
