<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Personal Development</name>
   <tag></tag>
   <elementGuidId>592a991c-6ecc-46f5-a8ff-a9cc51468fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.css-dcd3y</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div[2]/div[2]/div[2]/div/a/div/span/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77642f52-0e62-40b8-ba9f-c35ca97b4126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-dcd3y</value>
      <webElementGuid>47d357eb-4393-4dcc-84e9-7be444d0aa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal Development</value>
      <webElementGuid>09f44ff4-1b87-40e8-8329-aab76afdc65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1yahoi5&quot;]/div[@class=&quot;css-52pv4t&quot;]/div[@class=&quot;css-2m5ue8&quot;]/div[@class=&quot;css-1qftkdc&quot;]/div[@class=&quot;css-mp7xkt&quot;]/a[@class=&quot;css-1yahoi5&quot;]/div[@class=&quot;css-p2q30o&quot;]/span[@class=&quot;css-1vlpotx&quot;]/div[@class=&quot;css-1cwfiz9&quot;]/span[@class=&quot;css-dcd3y&quot;]</value>
      <webElementGuid>11803b0f-7201-4d27-9f9f-8ac795fa8847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div[2]/div[2]/div[2]/div/a/div/span/div/span</value>
      <webElementGuid>9c7f5377-3423-4042-9c16-1616626a7ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all'])[1]/following::span[2]</value>
      <webElementGuid>3c15677c-0466-479e-940b-05311f09bf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse by topics'])[1]/following::span[3]</value>
      <webElementGuid>e35656ed-bb1f-4977-bba3-eca667fb28fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety and Compliance'])[1]/preceding::span[1]</value>
      <webElementGuid>f200e502-2f6e-42a3-b725-c3ab8612c7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology Skills'])[1]/preceding::span[3]</value>
      <webElementGuid>70fbc4fa-336a-4e48-a643-82e194745925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Personal Development']/parent::*</value>
      <webElementGuid>2e7da8c3-3a11-493b-8c51-ff34f188ea84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span</value>
      <webElementGuid>e3bfabaf-231b-4804-9bea-13da021aa4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Personal Development' or . = 'Personal Development')]</value>
      <webElementGuid>39f7b38e-45cf-420e-a6bf-de3e1272ee8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
