<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>7da8ab88-8523-4c37-b35e-b38aef34c390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-app.shadow-2.btn-primary.m-r-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c79f87d4-c209-4e4f-a59e-00048b9156ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83091e0f-3ba7-45aa-af43-0b4d8632e383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-app shadow-2 btn-primary m-r-sm</value>
      <webElementGuid>7435b01c-c714-4d97-bd2e-4a4464661603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[primary.class, { 'btn-primary': !primary.class }, {'m-r-sm': $ctrl.options.secondary &amp;&amp; $ctrl.options.secondary.length || $index !== $ctrl.options.primary.length - 1}]</value>
      <webElementGuid>b9555381-c67d-4cf8-bb75-27ada56c23c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>primary.click()</value>
      <webElementGuid>c0249e27-aa88-4064-bf61-2da0caf03381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>primary in $ctrl.options.primary track by $index</value>
      <webElementGuid>551b4c3d-9432-45f4-a354-ce7b2f518699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!primary.widgetOptions</value>
      <webElementGuid>ae3f3644-8570-418d-978d-4b97f86f7647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-enable</name>
      <type>Main</type>
      <value>primary.tooltip</value>
      <webElementGuid>8f828bce-098b-4b7a-add7-290bbe173b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>1fb6f306-fe10-4d6a-834c-e26116c15a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-class</name>
      <type>Main</type>
      <value>go1d-tooltip-container</value>
      <webElementGuid>3afd4929-45f9-46d4-9cfd-aa736cff0871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create...</value>
      <webElementGuid>d384848b-b339-4749-bb37-d5294ae73b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-inner&quot;)/div[@class=&quot;app-uiview&quot;]/admin-nav[1]/div[@class=&quot;page-admin&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;admin-view&quot;]/div[1]/admin-manage-users[1]/div[@class=&quot;page--heading admin-page--heading&quot;]/apiom-heading[1]/div[@class=&quot;page--actions pull-right&quot;]/apiom-buttons[1]/button[@class=&quot;btn btn-app shadow-2 btn-primary m-r-sm&quot;]</value>
      <webElementGuid>9a8b1b7e-69c9-419d-ab67-30254ea11d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>78864572-8a0b-451e-9cb5-c2489ddf589a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-inner']/div/admin-nav/div/div[2]/div/div/admin-manage-users/div/apiom-heading/div/apiom-buttons/button</value>
      <webElementGuid>8a596851-a2dd-4189-a5b1-22035d640077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[2]/following::button[1]</value>
      <webElementGuid>45962c28-d634-4205-ab40-f77321a8ef95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[3]/following::button[1]</value>
      <webElementGuid>d0d6ac90-1ce7-4cb8-84b7-00c29e85ecc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import...'])[1]/preceding::button[2]</value>
      <webElementGuid>a39e9fc5-c429-4f76-8045-397840213c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create...']/parent::*</value>
      <webElementGuid>ecaa1d7b-0065-4031-8cc6-72bb721b4c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//apiom-buttons/button</value>
      <webElementGuid>bb950e3a-f48f-4d2c-a8da-d6d7c50497aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Create...' or . = 'Create...')]</value>
      <webElementGuid>1036f6ea-67ae-406c-ba25-fac5f718db29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
