<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mavic.aquinoemids.com</name>
   <tag></tag>
   <elementGuidId>afaa13ea-6c36-4e8a-b943-2c64a5acf307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1684585474214-1-uiGrid-00O2-cell > div.ui-grid-cell-contents</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1684585474214-1-uiGrid-00O2-cell']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c935467f-0b0c-4e64-b392-3c8772d9d5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-grid-cell-contents</value>
      <webElementGuid>d7e5a269-c37b-425e-9981-5c1d536c92e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mavic.aquino@emids.com</value>
      <webElementGuid>75968243-014c-491b-b7da-7be791420dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1684585474214-1-uiGrid-00O2-cell&quot;)/div[@class=&quot;ui-grid-cell-contents&quot;]</value>
      <webElementGuid>e0f9724c-7d3b-4d7d-a3b9-664ac0a94fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1684585474214-1-uiGrid-00O2-cell']/div</value>
      <webElementGuid>0cc6b495-fcfb-420f-ad8d-f4520cb0da2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[10]</value>
      <webElementGuid>1f87b23d-e649-4b0b-aa45-2ece16cbdfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learner'])[1]/following::div[12]</value>
      <webElementGuid>a148bda7-f3d3-4e20-8d0e-7f8284ae0b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learner, Manager'])[1]/preceding::div[1]</value>
      <webElementGuid>8b803e5e-86b9-4032-a9d2-092cff2ab118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::div[3]</value>
      <webElementGuid>db337efc-dd68-4ed0-9612-72b4aeabd08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mavic.aquino@emids.com']/parent::*</value>
      <webElementGuid>e2041058-b3b8-499e-8bd4-224feaf3fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>c08d891f-2d07-4323-9e00-653098ae881f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'mavic.aquino@emids.com' or . = 'mavic.aquino@emids.com')]</value>
      <webElementGuid>4e47d565-95b5-401c-8f54-57212e6e379c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
