<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Users</name>
   <tag></tag>
   <elementGuidId>927c5cc6-23ef-4db2-94b8-66ad5b6aaebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.pull-left.m-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box-inner']/div/my-team-container/div[2]/div/my-team-users/div/apiom-heading/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>8caf24ca-b290-4d8b-b1df-a53a5629bffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left m-0</value>
      <webElementGuid>740008d5-8d38-4df5-ac24-741ca666727e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>50a978ae-48a4-4d74-b7bf-96b54dcebd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-inner&quot;)/div[@class=&quot;app-uiview&quot;]/my-team-container[1]/div[@class=&quot;container&quot;]/div[1]/my-team-users[1]/div[@class=&quot;page--heading clearfix m-t-sm m-b-lg&quot;]/apiom-heading[1]/h3[@class=&quot;pull-left m-0&quot;]</value>
      <webElementGuid>24005586-509a-4d36-abdd-5de38f54282f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-inner']/div/my-team-container/div[2]/div/my-team-users/div/apiom-heading/h3</value>
      <webElementGuid>e712096e-8c38-4206-85ff-fec671bd61a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrollments'])[1]/following::h3[1]</value>
      <webElementGuid>54dd71b2-7fbe-4e2a-9b70-9bcbbefb6be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::h3[1]</value>
      <webElementGuid>e5b90726-526a-4e19-a3c9-c4c0f13fafee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User management'])[1]/preceding::h3[1]</value>
      <webElementGuid>510bfea9-2df2-4c67-b082-c1ea1e1afaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>abd2fe9a-8327-4c86-9c41-2df9d5577634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>09ea8620-70c7-493c-b29e-0f67f1d4e8de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
