<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User management_form-control ng-prist_51bffd</name>
   <tag></tag>
   <elementGuidId>bfdd09f8-fd32-4ba1-9929-63402e145cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7281a34c-c6fd-46cf-9343-5544a9a4b0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>533fafa2-0651-427c-a70e-1291cbcac50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>38c1d6fd-6208-494a-b475-96802bb18b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e029fd97-b007-445b-a8b6-f7459dd40963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.query</value>
      <webElementGuid>d043391b-e49b-4e09-a1b7-5e4466abc0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>$event.keyCode == 13 ? $ctrl.search() : null</value>
      <webElementGuid>4367c20c-8752-4cad-be8b-a6bd4dfa2b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d44dc395-2883-484c-8d74-2441d941f85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-inner&quot;)/div[@class=&quot;app-uiview&quot;]/admin-nav[1]/div[@class=&quot;page-admin&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;admin-view&quot;]/div[1]/admin-manage-users[1]/report[1]/ng-include[1]/report-full[1]/section[@class=&quot;report-builder&quot;]/section[@class=&quot;report-content&quot;]/report-display[1]/ng-include[1]/report-display-table[1]/div[@class=&quot;report--header-container&quot;]/header[@class=&quot;report-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 col-xs-5&quot;]/report-search[1]/div[@class=&quot;form-group report-search-box&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>4e78b786-f576-462b-902b-3493819f3372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>7ec0f093-9d36-4691-b2ef-d1e6f628b97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-inner']/div/admin-nav/div/div[2]/div/div/admin-manage-users/report/ng-include/report-full/section/section/report-display/ng-include/report-display-table/div/header/div/div/report-search/div/input</value>
      <webElementGuid>578dbe29-81a4-406f-adb4-6ef5ea82f649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//report-search/div/input</value>
      <webElementGuid>379c3955-6313-44d7-8470-20005a848c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>cac23f65-1a39-493b-8efe-5bbcef38fef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
