<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Groups_topSearchDesktop</name>
   <tag></tag>
   <elementGuidId>868216e4-9d01-45e0-b7f1-fd35f4366ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topSearchDesktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='topSearchDesktop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5409651-f3f5-4d84-8725-bbea553f5847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1gc701u</value>
      <webElementGuid>dd6694d5-43e2-40e9-8df3-69c452293eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topSearchDesktop</value>
      <webElementGuid>b440b56d-3def-49a8-8eca-8f10dc4aa632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a05e0ca-5183-4828-a11f-b809fe5d1430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search…</value>
      <webElementGuid>560ac3f8-4201-44e7-a560-30298eb5c8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>inputElement</value>
      <webElementGuid>99bf9658-04be-4e31-940b-6da0b58c8e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Field</value>
      <webElementGuid>951b7c91-78b7-4f25-989a-4ea4f0eabe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>6e35e524-bb42-4ab8-9e6d-078fe577ffdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>60deca1b-9793-43ce-bc83-ca48aac0d177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topSearchDesktop&quot;)</value>
      <webElementGuid>da8130d4-ec70-4ea0-90b5-6142574f7834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='topSearchDesktop']</value>
      <webElementGuid>e6eddb72-4287-4d97-944e-9b7e8280cac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downshift-1-label']/div/input</value>
      <webElementGuid>020af947-2bbc-4ae7-94f0-aa4cefbae73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>486c36e5-9217-43dc-8509-758c98164bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'topSearchDesktop' and @type = 'text' and @placeholder = 'Search…']</value>
      <webElementGuid>fe11ad77-449b-44c6-b3fc-7d8caed82499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
