<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Groups_topSearchDesktop_1</name>
   <tag></tag>
   <elementGuidId>6e5d4ce6-1473-4ef1-af95-0c37578917e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topSearchDesktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='topSearchDesktop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd3f9c78-6bea-4080-a1b7-0be85e876654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1gc701u</value>
      <webElementGuid>667cbc27-9037-48ed-90e9-d8fa0fdf8c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topSearchDesktop</value>
      <webElementGuid>c7b2ee5c-0e79-4a1e-b682-47341a0a0f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d133154-6595-43d0-8f8c-13b261058ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search topics, courses and resources…</value>
      <webElementGuid>580ab147-cd8f-489e-b1bd-f5dd6bc7aeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>inputElement</value>
      <webElementGuid>d6bf7071-f416-42c0-b316-672818cabc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Field</value>
      <webElementGuid>ead771aa-05b4-4f69-b361-8bd8bf32085d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>e2c8cd88-c7bc-4696-8870-d867477d811a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a66fe916-49b6-4922-a5ad-71eb4d5d6dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-1-menu</value>
      <webElementGuid>24d2208a-b147-439d-831b-4b89712cd219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topSearchDesktop&quot;)</value>
      <webElementGuid>c76c45b6-8588-43d2-a7d5-46f373f2b112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='topSearchDesktop']</value>
      <webElementGuid>1fafef8f-b636-40f2-abc0-af11362011c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downshift-1-label']/div/input</value>
      <webElementGuid>a0ad888a-ebc1-4476-a1e7-c1813bde2c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>07fbb023-ef7c-426a-864d-0b7d42ccfcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'topSearchDesktop' and @type = 'text' and @placeholder = 'Search topics, courses and resources…']</value>
      <webElementGuid>13ed8973-956a-4f2a-b8a9-ac3430ba5f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
