<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Content Administrator_manager</name>
   <tag></tag>
   <elementGuidId>990cfe56-1b7a-4373-aed3-ea5239a0c5b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manager</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manager']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29565d34-08c5-4767-8970-0af6ee2ccd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>38a2cc05-9350-4d61-aa31-1c5cf0f3df20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manager</value>
      <webElementGuid>df16aeb8-1d02-4ccd-a631-fd5d3ae30f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-checklist-value</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>34b18dfc-d4c3-417f-9550-36c378caced0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>item.id === 'Student'</value>
      <webElementGuid>6d15a19b-85ca-41e4-a2a2-e51785c4ae18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$ctrl.onChangeRole(item)</value>
      <webElementGuid>4db9a3a9-5e16-4fae-a4d2-6c518fcd5be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>75e20e0e-e00b-4772-a509-155dc99a9d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>0d5f6ff0-5dba-485b-919a-58e608eaa6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-checklist-model</name>
      <type>Main</type>
      <value>$ctrl.inputUser.roles</value>
      <webElementGuid>9d63a9c0-aab4-40b1-b3a0-8576a4d469de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ab0063d-0e1b-43bb-b916-0d9dd064aedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97fd86e0-e395-4f2f-b044-39725ab80f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bcf89994-93fa-430d-93f8-ab7d5c1d04a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manager&quot;)</value>
      <webElementGuid>c2d112c9-ca17-467a-b87d-a740ecd6647a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manager']</value>
      <webElementGuid>4b1e5d21-bb4c-4b80-88ce-872568302a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>bdf974d6-5bca-43bd-8c5c-8d5033a23169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'manager']</value>
      <webElementGuid>f842a43a-10ce-4718-8234-8983bad0f139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
